language: generic
sudo: required
dist: xenial

install:
  - gem install coveralls-lcov
  - sudo apt-get install lcov

jobs:
  include:
    - stage: build docker image
      script:
        - git checkout ${TRAVIS_BRANCH}
        - git rev-parse --abbrev-ref HEAD
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - docker run -e COVERALLS_TOKEN=${COVERALLS_TOKEN}
          --rm ${DOCKER_USERNAME}/rocnnet-test

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false
