language: generic
sudo: required
dist: xenial

cache:
  directories:
  - $HOME/travistest-dep
  - $HOME/prototxts

install:
- sudo bash -x $TRAVIS_BUILD_DIR/travis.sh $HOME/travistest-dep $TRAVIS_BUILD_DIR

before_script:
# coverage then make build dir
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters
- mkdir build

script:
# build with test enabled
- cd ${TRAVIS_BUILD_DIR}/build
- cmake -DTENNCOR_TEST=ON -DCMAKE_CXX_COMPILER=g++-6 ${TRAVIS_BUILD_DIR}
- cmake --build .
# run tests
- ${TRAVIS_BUILD_DIR}/bin/bin/gd_demo $HOME/prototxts
- ${TRAVIS_BUILD_DIR}/tenncor/bin/bin/tenncortest --gtest_break_on_failure --gtest_repeat=50 --gtest_shuffle
- cat fuzz.out

after_success:
# coverage log
- cd ${TRAVIS_BUILD_DIR}
- lcov --version
- gcov --version
- lcov --directory . --gcov-tool gcov-6 --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info '**/gtest*' '**/tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug < see coverage here
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

# safelist
branches:
  only:
  - master
  - stable
  - experimental

notifications:
  email: false