language: generic
sudo: required
dist: xenial

install:
  - gem install coveralls-lcov
  - sudo apt-get install lcov

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/shareds
        - docker run
          -e SHARED_DIR=/shareds
          -v ${TRAVIS_BUILD_DIR}/shareds:/shareds
          --rm ${DOCKER_USERNAME}/rocnnet-test

after_success:
  - pushd ${TRAVIS_BUILD_DIR}/shareds
  - lcov --version
  - gcov --version
  - lcov --base-directory . --directory . --gcov-tool gcov --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '**/gtest*' '**/tests/*' '**/ipython/*' '**/bin/*' '**/build/*' '/usr/include/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
  - popd

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false
