language: generic
sudo: required
dist: xenial

install:
  - gem install coveralls-lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - make -C lcov-1.13/ install

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/shareds
        - docker run
          -e SHARED_DIR=/shareds
          -v ${TRAVIS_BUILD_DIR}/shareds:/shareds
          --rm ${DOCKER_USERNAME}/rocnnet-test

after_success:
  - mv -R ${TRAVIS_BUILD_DIR}/shareds/app ${TRAVIS_BUILD_DIR}/app
  - lcov --version
  - gcov --version
  - lcov --base-directory . --directory . --gcov-tool gcov-6 --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '**/gtest*' '**/tests/*' '**/ipython/*' '**/bin/*' '**/build/*' '/usr/include/*' --output-file coverage.info # filter out system and test code
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false
