language: generic
sudo: required
dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - echo $TRAVIS_BRANCH
        - docker run -e COVERALLS_TOKEN=$COVERALLS_TOKEN
          -e CI_NAME=rocnnet
          -e CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
          -e CI_BRANCH=$TRAVIS_BRANCH
          -e CI_BUILD_URL=https://travis-ci.org/mingkaic/rocnnet/jobs/$TRAVIS_BUILD_ID
          --rm $DOCKER_USERNAME/rocnnet-test

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false
