language: generic
sudo: required
dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - docker run --rm $DOCKER_USERNAME/rocnnet-test

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false