language: generic
sudo: required
dist: xenial

install:
  - gem install coveralls-lcov

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - mkdir $TRAVIS_BUILD_DIR/shareds
        - docker run
          -e SHARED_DIR=/host_shareds
          -v ${TRAVIS_BUILD_DIR}/shareds:/host_shareds
          --rm ${DOCKER_USERNAME}/rocnnet-test

after_success:
  - lcov --list coverage.info # debug < see coverage here
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} ${TRAVIS_BUILD_DIR}/shareds/coverage.info # uploads to coveralls

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false
