language: generic
sudo: required
dist: xenial

install:
  - gem install coveralls-lcov
  - sudo apt-get install lcov

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker-compose build
        - docker images
        - docker-compose push
    - stage: test
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/shareds
        - docker run
          -e COVERALLS_TOKEN=${COVERALLS_TOKEN}
          -e CI=true
          -e TRAVIS=true
          -e CONTINUOUS_INTEGRATION=true
          -e TRAVIS_BRANCH=${TRAVIS_BRANCH}
          --rm ${DOCKER_USERNAME}/rocnnet-test

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false
