language: generic
sudo: required
dist: xenial

cache:
  directories:
  - $HOME/rocnnet-dep
  - $HOME/prototxts

install:
- sudo bash -x $TRAVIS_BUILD_DIR/travis.sh $HOME/rocnnet-dep $TRAVIS_BUILD_DIR

script:
- bash tests.sh $HOME/prototxts

# safelist
branches:
  only:
  - master
  - stable
  - experimental

# no need to pollute inboxes
notifications:
  email: false