version: '2'

services:
  ubuntu-release:
    image: mkaichen/rocnnet-ubuntu:latest
    build:
      context: .
      dockerfile: dockerbuilds/Dockerfile-ubuntu

  ubuntu-test:
    image: mkaichen/rocnnet-test:latest
    build:
      context: .
      dockerfile: dockerbuilds/Dockerfile-test
