# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extenncor/dqntrainer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='extenncor/dqntrainer.proto',
  package='dqn',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x65xtenncor/dqntrainer.proto\x12\x03\x64qn\"I\n\x08\x45xpBatch\x12\x0f\n\x07\x61\x63t_idx\x18\x01 \x01(\x05\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0b\n\x03obs\x18\x03 \x03(\x02\x12\x0f\n\x07new_obs\x18\x04 \x03(\x02\"t\n\x06\x44qnEnv\x12\x18\n\x10\x61\x63tions_executed\x18\x01 \x01(\x05\x12\x15\n\rntrain_called\x18\x02 \x01(\x05\x12\x15\n\rnstore_called\x18\x03 \x01(\x05\x12\"\n\x0b\x65xperiences\x18\x04 \x03(\x0b\x32\r.dqn.ExpBatchb\x06proto3')
)




_EXPBATCH = _descriptor.Descriptor(
  name='ExpBatch',
  full_name='dqn.ExpBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='act_idx', full_name='dqn.ExpBatch.act_idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='dqn.ExpBatch.reward', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obs', full_name='dqn.ExpBatch.obs', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_obs', full_name='dqn.ExpBatch.new_obs', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=108,
)


_DQNENV = _descriptor.Descriptor(
  name='DqnEnv',
  full_name='dqn.DqnEnv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions_executed', full_name='dqn.DqnEnv.actions_executed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ntrain_called', full_name='dqn.DqnEnv.ntrain_called', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nstore_called', full_name='dqn.DqnEnv.nstore_called', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='experiences', full_name='dqn.DqnEnv.experiences', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=226,
)

_DQNENV.fields_by_name['experiences'].message_type = _EXPBATCH
DESCRIPTOR.message_types_by_name['ExpBatch'] = _EXPBATCH
DESCRIPTOR.message_types_by_name['DqnEnv'] = _DQNENV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpBatch = _reflection.GeneratedProtocolMessageType('ExpBatch', (_message.Message,), dict(
  DESCRIPTOR = _EXPBATCH,
  __module__ = 'extenncor.dqntrainer_pb2'
  # @@protoc_insertion_point(class_scope:dqn.ExpBatch)
  ))
_sym_db.RegisterMessage(ExpBatch)

DqnEnv = _reflection.GeneratedProtocolMessageType('DqnEnv', (_message.Message,), dict(
  DESCRIPTOR = _DQNENV,
  __module__ = 'extenncor.dqntrainer_pb2'
  # @@protoc_insertion_point(class_scope:dqn.DqnEnv)
  ))
_sym_db.RegisterMessage(DqnEnv)


# @@protoc_insertion_point(module_scope)
