FROM ubuntu:latest

ARG TEST_ENV=0

ENV SETUP_DIR /usr/src/rocnnet_setup

RUN mkdir -p $SETUP_DIR
WORKDIR $SETUP_DIR

COPY ./scripts $SETUP_DIR

# standard setup
RUN bash ./ubuntu_setup.sh

# setup analysis tools IF we're testing
RUN if [ "$TEST_ENV" -eq "1" ]; \
	then \
		bash ./ubuntu_analysis.sh; \
	fi
