#include "../memory/allocator.hpp"
#include "../memory/session.hpp"
#include "../variable/variable.hpp"
#include "../variable/operation.hpp"
#include "../variable/elementary.hpp"
#include "../variable/functions.hpp" // encompass all operation
#include "../variable/mat_ops.hpp"
#include "../tensor.hpp"
#include "../tensorshape.hpp"
#include "../optimization/optimizer.hpp"
#include "../optimization/update.hpp"