FROM mkaichen/rocnnet-ubuntu-env:latest

ENV APP_DIR /usr/src/rocnnet

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

COPY ./app $APP_DIR

# build rocnnet
RUN mkdir build && cd build && \
	cmake -DTENNCOR_TEST=OFF -DLCOVERAGE=OFF .. && \
	cmake --build .;
