FROM mkaichen/rocnnet-test-env:latest

ENV RBUILD_DIR /usr/src/rocapp

RUN mkdir -p $RBUILD_DIR
WORKDIR $RBUILD_DIR

COPY ./app $RBUILD_DIR

# build rocnnet
RUN mkdir build && cd build && \
    cmake -DTENNCOR_TEST=ON .. && \
    cmake --build .;

CMD [ "bash", "./scripts/test/tests.sh", "|", "tee" ]
