FROM mkaichen/rocnnet-ubuntu-env:latest

ENV RBUILD_DIR /usr/src/rocapp

RUN mkdir -p $RBUILD_DIR
WORKDIR $RBUILD_DIR

COPY ./app $RBUILD_DIR

# build rocnnet
RUN mkdir build && cd build && \
    cmake -DTENNCOR_TEST=OFF -DLCOVERAGE=OFF .. && \
    cmake --build .;
